bridge:
  kafka:
    topic: ${KAFKA_TOPIC}
    group-id: ${KAFKA_GROUP_ID}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  telegram:
    token: ${TELEGRAM_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}
    footer: ${TELEGRAM_FOOTER}
